# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
backend: pacman

# Como es una instalación de "Copia exacta" (unpackfs), no necesitamos
# actualizar la base de datos ni el sistema durante la instalación para 
# evitar romper cosas si el usuario no tiene internet.
skip_if_no_internet: false
update_db: false
update_system: false

pacman:
    num_retries: 0
    disable_download_timeout: false
    needed_only: false

operations:
  - try_remove:
      # 1. El instalador en sí (ya no se necesita en el sistema final despues de todo, XD)
      - calamares
      
      # 2. Herramientas exclusivas del LiveCD/ISO
      - mkinitcpio-archiso
      - squashfs-tools
      
      # 3. (Opcional) Dependencias pesadas de Calamares que no usas en Hyprland
      # Calamares usa Qt5 y kpmcore. Si tu entorno Hyprland y tus apps no 
      # necesitan estas librerías, puedes borrarlas para ahorrar espacio, de nada,  jejejejeje.
      - kpmcore
      - yaml-cpp
      - ckbcomp
