---
efiSystemPartition: "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend
drawPartitionLabels: true
allowManualPartitioning: true
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType: "btrfs"
