---
efiSystemPartition:     "/boot"
defaultFileSystemType:     "ext4"
availableFileSystemTypes:  ["ext4", "btrfs"]

# Forzar los modos automatizados
availableFeatures: [ erase, manual, replace ]
defaultPartitionTableType: "gpt"

userSwapChoices:
    - none
    - small

# 🔥 EL PARCHE: Bajamos los requisitos del formateador automático
requirements:
    requiredDiskSpace: 5.0
