---
# Configuración global para gestionar servicios de Systemd al final de la instalación.
# Calamares aplicará esto haciendo chroot automáticamente en el sistema de destino.

units:
  - name: "NetworkManager"
    action: "enable"

  - name: "greetd"
    action: "enable"

  - name: "bluetooth"
    action: "enable"
    mandatory: false  # No rompe la instalación si el usuario no tiene bluetooth
