# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
i18n:
     name: "Finalizando ajustes, configurando Greetd y Limine Bootloader..."

# Ejecutar dentro del sistema recién instalado (chroot)
dontChroot: false

# Aumentamos a 120 segundos para darle tiempo de sobra al script de Limine
timeout: 120

script:
    # =========================================================
    # 1. LIMPIEZA DE ARCHIVOS DEL ENTORNO LIVE
    # =========================================================
    # (Nota: Como dontChroot es false, no hace falta usar ${ROOT}, 
    # todos los comandos corren directamente en la raíz / del nuevo disco)
    
    # Reglas temporales de sudo y polkit de la ISO
    - "-rm -f /etc/sudoers.d/g_wheel"
    - "-rm -f /etc/polkit-1/rules.d/49-nopasswd_global.rules"
    - "-rm -f /etc/polkit-1/rules.d/49-nopasswd-calamares.rules"
    
    # Servicios temporales de pacman y tty de la ISO
    - "-rm -rf /etc/mkinitcpio.conf.d/"
    - "-rm -rf /etc/systemd/system/getty@tty1.service.d"
    - "-rm -rf /etc/systemd/system/multi-user.target.wants/pacman-init.service"
    - "-rm -f /etc/systemd/system/pacman-init.service"
    - "-rm -f /etc/systemd/system/etc-pacman.d-gnupg.mount"
    
    # Scripts de auto-arranque del LiveCD
    - "-rm -f /root/.automated_script.sh"
    - "-rm -f /root/.zlogin"
    
    # Eliminar el rastro del gestor de sesiones antiguo
    - "-rm -f /etc/systemd/system/display-manager.service"

    # =========================================================
    # 2. CONFIGURACIÓN DE GREETD (Wayland Login Manager)
    # =========================================================
    # Eliminar la sección [initial_session] para matar el auto-login del usuario Live.
    # El comando sed buscará "[initial_session]" y las siguientes 2 líneas y las borrará.
    - "sed -i '/^\\[initial_session\\]/,+2d' /etc/greetd/config.toml"
    
    # Habilitar Greetd para que inicie automáticamente al encender la PC
    - "systemctl enable greetd.service"

    # =========================================================
    # 3. INSTALACIÓN DEL BOOTLOADER (LIMINE)
    # =========================================================
    # Llamamos a tu script personalizado para instalar Limine
    - command: "/usr/local/bin/install-limine.sh"
