---
defaultShell: /bin/zsh
allowRoot: true
forcedRootPassword: false
passwordRequirements:
    minLength: 4
    maxLength: -1
    letterRequirement: 0
    digitRequirement: 0
    specialRequirement: 0
