---
showSupportUrl:         true
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false

requirements:
    requiredStorage:    15
    requiredRam:        1.5
    internetCheckUrl:   http://example.com
    check:
        - storage
        - ram
        - power
