---
# Mostrar u ocultar enlaces de la comunidad en la pantalla de bienvenida
showSupportUrl:         true
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false

# 🔥 LOS REQUISITOS: Aquí bajamos la barra para que no esconda opciones
requirements:
    requiredRAM:        1.0   # Solo pide 1GB de RAM mínimo para instalar
    requiredDiskSpace:  5.0   # Bajamos el espacio mínimo a 5GB para las pruebas
    requiredPower:      false # No exige estar conectado a la corriente
    requiredInternet:   false # No exige internet
    requiredRoot:       true  # Obviamente sí exige ser root
