$wallpaper = /home/angelito/Imágenes/Wallpapers/892379.png
$background = 1a110e
$foreground = f1dfd8

$primary = ffb596
$secondary = f5b9a0
$tertiary = cdcc57
$surface = 1a110e
$surface_bright = 423732
$outline = a38c82
$error = 000000

$shadow = 000000
