---
modules-search: [ local ]

instances: []

sequence:
  # 1. Fase de Configuración (Visual)
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users

  # 2. Fase de Ejecución (En segundo plano)
  - exec:
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localegen
    - networkcfg
    - hwclock
    - displaymanager
    - services-systemd
    - shellprocess

  # 3. Fase Final
  - show:
    - finished

branding: atomic
prompt-on-quit: true
backend: pacman
